# Generated by Django 5.0.1 on 2024-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workout_type', models.CharField(choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength training'), ('FLEXIBILITY', 'Flexibility exercise'), ('BALANCE', 'Balance exercise'), ('HIIT', 'High-Intensity Interval Training'), ('CIRCUIT', 'Circuit Training'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
            ],
        ),
    ]
